# Reads every rules/*.yaml under RULES_DIR and writes a single .cpp file at
# OUT_FILE whose sole content is a static vector of {filename, yaml_source}
# pairs.  Invoked from src/core/CMakeLists.txt via
#   cmake -DRULES_DIR=... -DOUT_FILE=... -P cmake/GenerateBuiltinRules.cmake
# so the embedding happens at build time, not configure time, and re-runs
# whenever any rule YAML changes.

if(NOT DEFINED RULES_DIR)
    message(FATAL_ERROR "GenerateBuiltinRules.cmake: RULES_DIR is required")
endif()
if(NOT DEFINED OUT_FILE)
    message(FATAL_ERROR "GenerateBuiltinRules.cmake: OUT_FILE is required")
endif()

file(GLOB rule_files "${RULES_DIR}/*.yaml" "${RULES_DIR}/*.yml")
list(SORT rule_files)   # stable output; incremental builds don't churn

# CMake treats semicolons in string args to file(WRITE) as list separators
# unless the whole thing is one string. Assemble the whole file into `out`
# and write it once at the end.
set(out "")
string(APPEND out "// AUTO-GENERATED by cmake/GenerateBuiltinRules.cmake. Do not edit.\n")
string(APPEND out "\n")
string(APPEND out "#include \"alps/core/builtin_rules.hpp\"\n")
string(APPEND out "\n")
string(APPEND out "namespace alps::core {\n")
string(APPEND out "\n")
string(APPEND out "const std::vector<BuiltinRuleSource>& builtin_rule_sources() {\n")
string(APPEND out "    static const std::vector<BuiltinRuleSource> data = {\n")

foreach(rule_path IN LISTS rule_files)
    file(READ "${rule_path}" yaml)
    get_filename_component(name "${rule_path}" NAME)
    # Raw string delimiter `ALPSRULE` is unlikely to appear inside any rule
    # YAML. If it ever does, `alps rules lint` will fail loudly on load.
    string(APPEND out "        {\"${name}\", R\"ALPSRULE(${yaml})ALPSRULE\"},\n")
endforeach()

string(APPEND out "    };\n")
string(APPEND out "    return data;\n")
string(APPEND out "}\n")
string(APPEND out "\n")
string(APPEND out "}  // namespace alps::core\n")

file(WRITE "${OUT_FILE}" "${out}")
